services:
  parc2025_ws:
    container_name: parc2025_ws
    image: thenoobinventor/parc-eng-2025-ws:latest
    ports:
    - '8080:8080'
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    tmpfs:
    - '/dev/shm:rw'
    volumes:
    - '/home/noobinventor/ros2_ws/src:/home/ubuntu/ros2_ws/src'
    - '/etc/timezone:/etc/timezone:ro'
    environment:
    - DISPLAY_SIZEW=1920
    - DISPLAY_SIZEH=1080
    - DISPLAY_REFRESH=60
    - DISPLAY_DPI=96
    - DISPLAY_CDEPTH=24
    - PASSWD=mypasswd
    - SELKIES_ENCODER=nvh264enc
    - SELKIES_ENABLE_RESIZE=false
    - SELKIES_VIDEO_BITRATE=8000
    - SELKIES_FRAMERATE=60
    - SELKIES_AUDIO_BITRATE=128000
    - SELKIES_ENABLE_BASIC_AUTH=true
    - SELKIES_ENABLE_HTTPS=false