<?xml version="1.0"?>

<robot name="parc_robot_v2" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find parc_robot_description)/urdf/scout_wheel_type1.xacro" />
  <xacro:include filename="$(find parc_robot_description)/urdf/scout_wheel_type2.xacro" />

  <!-- Variables -->
  <xacro:property name="M_PI" value="3.14159" />

  <!-- Vehicle Geometries -->
  <xacro:property name="base_x_size" value="0.9250000" />
  <xacro:property name="base_y_size" value="0.380000" />
  <xacro:property name="base_z_size" value="0.210000" />

  <xacro:property name="wheelbase" value="0.498" />
  <xacro:property name="track" value="0.58306" />
  <xacro:property name="wheel_vertical_offset" value="-0.0702" />

  <xacro:property name="wheel_length" value="1.1653e-01" />
  <xacro:property name="wheel_radius" value="1.6459e-01" />

  <!-- Base link -->
  <link name="base_link">
      <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
              <mesh filename="package://parc_robot_description/meshes/base_link.dae" />
          </geometry>
      </visual>
      <collision>
          <origin xyz="0 0 0.008" rpy="0 0 0" />
          <geometry>
              <box size="${base_x_size} ${base_y_size} ${base_z_size}" />
          </geometry>
      </collision>
      <collision>
          <origin xyz="0 0 ${base_z_size/6}" rpy="0 0 0" />
          <geometry>
              <box size="${base_x_size/6} ${base_y_size*1.65} ${base_z_size/3}" />
          </geometry>
      </collision>
  </link>

  <link name="base_footprint"/>

  <!-- Base bumper -->
  <gazebo reference="base_link">
    <sensor name="base_collision_sensor" type="contact">
      <contact>
        <collision>base_footprint_fixed_joint_lump__base_link_collision</collision>
        <topic>base_collisions</topic>
      </contact>
      <always_on>true</always_on>
      <update_rate>5</update_rate>
    </sensor>
  </gazebo>

  <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${wheel_radius - wheel_vertical_offset}" rpy="0 0 0" />
      <parent link="base_footprint" />
      <child link="base_link" />
  </joint>

  <link name="inertial_link">
      <inertial>
          <mass value="40" />
          <origin xyz="0.0 0.0 0.0" />
          <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
      </inertial>
  </link>

  <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="inertial_link" />
  </joint>

  <!-- Scout wheel macros -->
  <!-- wheel labeled from 0 to 3, conter-clockwise, starting from front right wheel -->
  <!-- motor 1 and 2 (left side) are mechanically installed in a reversed direction -->
  <xacro:scout_wheel_type1 wheel_prefix="front_right">
      <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.142 0 0" />
  </xacro:scout_wheel_type1>
  <xacro:scout_wheel_type2 wheel_prefix="front_left">
      <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="3.142 0 0" />
  </xacro:scout_wheel_type2>
  <xacro:scout_wheel_type1 wheel_prefix="rear_left">
      <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="3.142 0 0" />
  </xacro:scout_wheel_type1>
  <xacro:scout_wheel_type2 wheel_prefix="rear_right">
      <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.142 0 0" />
  </xacro:scout_wheel_type2>

  <!-- Wheel bumpers -->
  <gazebo reference="front_left_wheel_link">
    <sensor name="front_left_collision_sensor" type="contact">
      <contact>
        <collision>front_left_wheel_link_collision</collision>
        <topic>front_left_collisions</topic>
      </contact>
      <always_on>true</always_on>
      <update_rate>5</update_rate>
    </sensor>
  </gazebo>

  <gazebo reference="front_right_wheel_link">
    <sensor name="front_right_collision_sensor" type="contact">
      <contact>
        <collision>front_right_wheel_link_collision</collision>
        <topic>front_right_collisions</topic>
      </contact>
      <always_on>true</always_on>
      <update_rate>5</update_rate>
    </sensor>
  </gazebo>

  <gazebo reference="rear_left_wheel_link">
    <sensor name="rear_left_collision_sensor" type="contact">
      <contact>
        <collision>rear_left_wheel_link_collision</collision>
        <topic>rear_left_collisions</topic>
      </contact>
      <always_on>true</always_on>
      <update_rate>5</update_rate>
    </sensor>
  </gazebo>

  <gazebo reference="rear_right_wheel_link">
    <sensor name="rear_right_collision_sensor" type="contact">
      <contact>
        <collision>rear_right_wheel_link_collision</collision>
        <topic>rear_right_collisions</topic>
      </contact>
      <always_on>true</always_on>
      <update_rate>5</update_rate>
    </sensor>
  </gazebo>

  <gazebo reference="base_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
  </gazebo>

  <gazebo reference="front_right_wheel_link">
    <mu1>0.9</mu1>
    <mu2>0.7</mu2>
    <!-- <mu1>0.2</mu1>
    <mu2>0.2</mu2> -->
    <kp>10000000.0</kp>
    <kd>0.0</kd>
    <!-- <kd>1.0</kd> -->
    <minDepth>0.001</minDepth>
  </gazebo>

  <gazebo reference="front_left_wheel_link">
    <mu1>0.9</mu1>
    <mu2>0.7</mu2>
    <!-- <mu1>0.2</mu1>
    <mu2>0.2</mu2> -->
    <kp>10000000.0</kp>
    <kd>0.0</kd>
    <!-- <kd>1.0</kd> -->
    <minDepth>0.001</minDepth>
  </gazebo>

  <gazebo reference="rear_left_wheel_link">
    <mu1>0.9</mu1>
    <mu2>0.7</mu2>
    <!-- <mu1>0.2</mu1>
    <mu2>0.2</mu2> -->
    <kp>10000000.0</kp>
    <kd>0.0</kd>
    <!-- <kd>1.0</kd> -->
    <minDepth>0.001</minDepth>
  </gazebo>

  <gazebo reference="rear_right_wheel_link">
    <mu1>0.9</mu1>
    <mu2>0.7</mu2>
    <!-- <mu1>0.2</mu1>
    <mu2>0.2</mu2> -->
    <kp>10000000.0</kp>
    <kd>0.0</kd>
    <!-- <kd>1.0</kd> -->
    <minDepth>0.001</minDepth>
  </gazebo>

  <!-- Sensor definitions -->
  <xacro:include filename="$(find parc_robot_description)/urdf/sensors.xacro" />
  <xacro:include filename="$(find parc_robot_description)/urdf/attachment.xacro" />
	
  <!-- Ros2 control -->
  <!-- <xacro:include filename="$(find parc_robot_description)/urdf/parc_robot_ros2_control.xacro" /> -->
  
  <!-- Gazebo diff drive plugin control -->
  <xacro:include filename="$(find parc_robot_description)/urdf/parc_robot_gz_control.xacro" />
  
</robot>
